### ISSUE TITLE
监听呢？

### ISSUE THREAD

**Issue by keyescgm** [wangtao2132/EditSpinner#2]
其数据变化的监听，回调呢？

**Comment by WrBug** [comment]
https://github.com/WrBug/EditSpinner/blob/master/editspinner/src/main/java/com/wrbug/editspinner/BaseEditSpinnerAdapter.java

参考下public abstract EditSpinnerFilter getEditSpinnerFilter();  方法不知道是不是你说的监听

**Comment by keyescgm** [comment]
比如说spinner，可以通过setonItemselectdListenner 来监听数据改变

**Comment by WrBug** [comment]
明白了，添加后再通知你

**Comment by WrBug** [comment]
你也可以自己实现一个BaseEditSpinnerAdapter ，在getView  里面自己实现监听就可以了

**Comment by WrBug** [comment]
v1.1.0修复
